# Generated by Django 4.1.3 on 2022-11-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cars',
            field=models.ManyToManyField(to='cars.car'),
        ),
    ]
