# Generated by Django 4.1.3 on 2022-11-15 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_rel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rel',
        ),
    ]
