# Generated by Django 4.1.3 on 2022-11-15 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_rel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rel',
        ),
    ]
